// Library build: four artifacts via Vite 8 (Rolldown) programmatic builds.
//
//   dist/docx-preview.js       UMD, readable, syntax lowered to Chrome 76
//   dist/docx-preview.min.js   UMD, terser-minified, Chrome 76
//   dist/docx-preview.mjs      ES module, readable, ES2020 syntax kept
//   dist/docx-preview.min.mjs  ES module, terser-minified, ES2020
//   dist/docx-preview.d.ts     generated by vite-plugin-dts (first cell only)
//
// UMD targets legacy embedders (Chrome 76 / FF 78 / Safari 13 / Edge 79):
// Oxc Transformer downlevels the syntax (no polyfills, same contract as the
// old Babel output plugin). The .mjs artifacts keep ES2020 for modern
// bundlers. jszip stays external and resolves to the global `JSZip` in UMD.
//
// Usage: node scripts/build-lib.mjs [--watch]
import { copyFile, rm } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'vite';
import dts from 'vite-plugin-dts';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const watch = process.argv.includes('--watch');

const banner = `/*
 * @license
 * @apollo-design/docx-preview <https://github.com/apollocmh/docx-preview>
 * Released under Apache License 2.0 — Copyright apollocmh
 * Based on docxjs by Volodymyr Baydalka <https://github.com/VolodymyrBaydalka/docxjs>
 */`;

const cells = [
	{ format: 'umd', target: 'chrome76', minify: false, file: 'docx-preview.js' },
	{ format: 'umd', target: 'chrome76', minify: 'terser', file: 'docx-preview.min.js' },
	{ format: 'es', target: 'es2020', minify: false, file: 'docx-preview.mjs' },
	{ format: 'es', target: 'es2020', minify: 'terser', file: 'docx-preview.min.mjs' },
];

// Drop the legacy flat viewer layout (dist/viewer.html, …) from pre-Vite
// builds so git sees the move and stale files don't ship.
for (const stale of ['viewer.html', 'viewer.js', 'viewer.css', 'jszip.min.js', 'fonts.json']) {
	await rm(resolve(root, 'dist', stale), { force: true });
}

for (const [i, cell] of (watch ? cells.slice(0, 1) : cells).entries()) {
	await build({
		configFile: false,
		root,
		logLevel: 'info',
		plugins: i === 0 ? [dts({ include: ['src'], bundleTypes: true, outDir: 'dist' })] : [],
		build: {
			outDir: 'dist',
			emptyOutDir: i === 0,
			sourcemap: true,
			target: cell.target,
			minify: cell.minify,
			watch: watch ? {} : null,
			lib: {
				entry: resolve(root, 'src/docx-preview.ts'),
				name: 'docx',
				formats: [cell.format],
				fileName: () => cell.file,
			},
			rolldownOptions: {
				external: ['jszip'],
				output: {
					banner,
					globals: { jszip: 'JSZip' },
				},
			},
		},
	});
	console.log(`built dist/${cell.file} (${cell.format}@${cell.target}${cell.minify ? ', min' : ''})`);
}

// The package is "type": "module", so Node would load a .js `require` target
// as ESM and the UMD factory would fall to its global branch. Ship the same
// UMD again as .cjs — the `require` condition gets real CJS exports while
// browsers keep the stable docx-preview.js filename.
if (!watch) {
	await copyFile(resolve(root, 'dist/docx-preview.js'), resolve(root, 'dist/docx-preview.cjs'));
	console.log('built dist/docx-preview.cjs (copy of docx-preview.js for the require entry)');
}
